// Curated free IPTV / live TV channels (HLS .m3u8)
// Sources: iptv-org public playlists. Replace/extend as needed.
export const liveChannels = [
  {
    id: 'redbull',
    name: 'Red Bull TV',
    category: 'Sports & Lifestyle',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Red_Bull_TV_logo.svg/320px-Red_Bull_TV_logo.svg.png',
    url: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
  },
  {
    id: 'nasa',
    name: 'NASA TV',
    category: 'Science',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_TV_logo.svg',
    url: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg TV',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Bloomberg_Television_logo.svg/320px-Bloomberg_Television_logo.svg.png',
    url: 'https://bloomberg.com/media-manifest/streams/us.m3u8',
  },
  {
    id: 'france24',
    name: 'France 24 English',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/France_24_logo.svg/320px-France_24_logo.svg.png',
    url: 'https://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8',
  },
  {
    id: 'dw',
    name: 'DW English',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/DW_logo_2012.svg/320px-DW_logo_2012.svg.png',
    url: 'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8',
  },
  {
    id: 'aljazeera',
    name: 'Al Jazeera English',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Al_jazeera_english_logo.svg/320px-Al_jazeera_english_logo.svg.png',
    url: 'https://live-hls-web-aje.getaj.net/AJE/01.m3u8',
  },
  {
    id: 'euronews',
    name: 'Euronews',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Euronews_logo_2016.svg/320px-Euronews_logo_2016.svg.png',
    url: 'https://euronews-live.akamaized.net/hls/live/2024292/euronews_en/master_3.m3u8',
  },
  {
    id: 'abc-au',
    name: 'ABC News Australia',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/ABC_News_channel_logo_2021.svg/320px-ABC_News_channel_logo_2021.svg.png',
    url: 'https://abc-iview-mediapackagestreams-2.akamaized.net/out/v1/6e1cc6d25ec0480ea099f6d125b76281/index.m3u8',
  },
  {
    id: 'cgtn',
    name: 'CGTN',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/CGTN_logo.svg/320px-CGTN_logo.svg.png',
    url: 'https://news.cgtn.com/resource/live/english/cgtn-news.m3u8',
  },
  {
    id: 'arirang',
    name: 'Arirang TV',
    category: 'Culture',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Arirang_TV_logo.svg/320px-Arirang_TV_logo.svg.png',
    url: 'https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8',
  },
  {
    id: 'cbsnews',
    name: 'CBS News',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/CBS_News_logo_2020.svg/320px-CBS_News_logo_2020.svg.png',
    url: 'https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8',
  },
  {
    id: 'bbc-world',
    name: 'BBC World News',
    category: 'News',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/BBC_News_2022.svg/320px-BBC_News_2022.svg.png',
    url: 'https://vs-cmaf-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_news_channel_hd/iptv_hd_abr_v1.mpd',
  },
];
